// Fonte de armazenamento de frases relacionadas ao jogo de digitação
const paragrafos = [
  "A prática leva à perfeição.",
  "Desenvolver com JavaScript é divertido e desafiador.",
  "Digitar rapidamente é uma habilidade útil em muitas profissões.",
  "Cada letra digitada corretamente conta pontos a seu favor.",
  "Respire fundo e mantenha o foco durante a digitação.",
  "Bons caminhos.",
  "Avisem a Kalil que eu li as normas.",
  "Supercalifragilisticexpialidocious.",
  "A resposta para a questão fundamental da vida, é o numero 42",
  "A vida é como um jogo de xadrez, sempre existe uma próxima jogada.",
  "Nunca é tarde demais para aprender algo novo.",
  "A persistência é o caminho do êxito.",
  "Grandes poderes trazem grandes responsabilidades.",
  "Que a força esteja com você.",
  "Ou você morre herói ou vive o suficiente para se tornar vilão.",
  "A primeira regra do Clube da luta é não falar sobre o Clube da luta.",
  "E pela primeira vez o rei sentiu medo.",
  "As vezes as questões são complicadas e as respostas são simples.",
  "Supere seus próprios limites.",
  "Nem homem nem nação podem existir sem uma ideia sublime.",
  "E tenho comigo pensado Deus é brasileiro e mora do meu lado.",
  "Pra que amanhã não seja só um ontem com um novo nome.",
  "Ao infinito e além.",
  "Carpe diem, aproveite o dia.",
  "Faça ou não faça, tentativa não há.",
  "O tempo é uma ilusão a hora do almoço duplamente.",
  "O inverno está chegando.",
  "Um lannister sempre paga suas dívidas.",
  "Quando você joga o jogo dos tronos, você ganha ou morre.",
  "Parte da jornada é o fim."
];
